In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'


from tqdm import tqdm

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
import mflow

In [3]:
import sys, os
print("CWD:: ",os.getcwd())
sys.path

CWD::  /mnt/externz/zRepoz/003_school/01_ocular/notebooks

['/mnt/externz/zRepoz/003_school/01_ocular/code/mflow',
 '/mnt/externz/zRepoz/003_school/01_ocular/code/mflow',
 '/mnt/externz/zRepoz/003_school/01_ocular/notebooks',
 '/home/bilha/anaconda3/lib/python37.zip',
 '/home/bilha/anaconda3/lib/python3.7',
 '/home/bilha/anaconda3/lib/python3.7/lib-dynload',
 '',
 '/home/bilha/anaconda3/lib/python3.7/site-packages',
 '/home/bilha/anaconda3/lib/python3.7/site-packages/locket-0.2.1-py3.7.egg',
 '/home/bilha/anaconda3/lib/python3.7/site-packages/IPython/extensions',
 '/home/bilha/.ipython']

In [4]:
from zdata import PdDataStats, ZPdDataset
import utilz, content 

pdstats = PdDataStats(
                {PdDataStats.DATA_DICT_RECORDZ_KEY: content.STARE_FUNDUS_CONTENT_FPATH,
                PdDataStats.DATA_DICT_HAS_HEADERZ_KEY: True,
                'rec_parser': utilz.FileIO.row_parser                     
                },
                 ftype=PdDataStats.TYPE_TXT_LINES_FILE ) 

pdstats.dframe

,fname,fpath,ishape,imin,imax,imean,istd,Normal,Emboli,BRAO,...,ASR,HTR,Coats,MA,CNV,UNDEF,dcodez_id,dcodez_short,dcodez_desc,dnotes
0,im0001,/mnt/externz/zRepoz/datasets/fundus/stare/im00...,"(605, 700, 3)",0,255,72.88491696182605,67.4625795519138,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7,BDR-NPDR,Background Diabetic Retinopathy,None
1,im0002,/mnt/externz/zRepoz/datasets/fundus/stare/im00...,"(605, 700, 3)",0,255,72.0751940181031,71.32206912730656,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,13++9,CNV++ASR,Choroidal Neovascularization++Arteriosclerotic...,Choroidal Neovascularization AND Arteriosclero...
2,im0003,/mnt/externz/zRepoz/datasets/fundus/stare/im00...,"(605, 700, 3)",0,255,88.61188665879575,83.22716701101746,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,14,UNDEF,Unknown Diagnosis,None
3,im0004,/mnt/externz/zRepoz/datasets/fundus/stare/im00...,"(605, 700, 3)",0,255,77.25434395907124,73.24522851098682,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,14++3,UNDEF++CRAO,Unknown Diagnosis++Cilio-Retinal Artery Occlusion,Cilio-Retinal Artery Occlusion OR Central Reti...
4,im0005,/mnt/externz/zRepoz/datasets/fundus/stare/im00...,"(605, 700, 3)",0,255,102.02467847304212,69.81886659922544,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3++5,CRAO++CRVO,Cilio-Retinal Artery Occlusion++Central Retina...,Central Retinal Artery Occlusion AND Central R...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,im0398,/mnt/externz/zRepoz/datasets/fundus/stare/im03...,"(605, 700, 3)",0,255,101.02690043290043,84.52555881724706,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,10++9,HTR++ASR,Hypertensive Retinopathy++Arteriosclerotic Ret...,Hypertensive Retinopathy AND Arteriosclerotic ...
393,im0399,/mnt/externz/zRepoz/datasets/fundus/stare/im03...,"(605, 700, 3)",0,255,115.21992916174734,80.85246464075023,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,2++1++9,BRAO++Emboli++ASR,Branch Retinal Artery Occlusion++Hollenhorst E...,Branch Retinal Artery Occlusion AND Hollenhors...
394,im0400,/mnt/externz/zRepoz/datasets/fundus/stare/im04...,"(605, 700, 3)",0,255,118.00685635576545,77.13519189468512,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,2++1++9,BRAO++Emboli++ASR,Branch Retinal Artery Occlusion++Hollenhorst E...,Branch Retinal Artery Occlusion AND Hollenhors...
395,im0401,/mnt/externz/zRepoz/datasets/fundus/stare/im04...,"(605, 700, 3)",0,255,95.07385832349469,92.740188763291,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,14,UNDEF,Unknown Diagnosis,None
396,im0402,/mnt/externz/zRepoz/datasets/fundus/stare/im04...,"(605, 700, 3)",0,255,94.89492561983471,98.05891465701379,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,14,UNDEF,Unknown Diagnosis,"Drusen, large"

In [5]:
pdstats.dframe[ (pdstats.dframe['UNDEF'] != '0.0') & (pdstats.dframe['UNDEF'] != '1.0')]

Empty DataFrame
Columns: [fname, fpath, ishape, imin, imax, imean, istd, Normal, Emboli, BRAO, CRAO, BRVO, CRVO, Hemi-CRVO, BDR-NPDR, PDR, ASR, HTR, Coats, MA, CNV, UNDEF, dcodez_id, dcodez_short, dcodez_desc, dnotes]
Index: []

[0 rows x 26 columns]

In [6]:
pdstats.dframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fname         397 non-null    object
 1   fpath         397 non-null    object
 2   ishape        397 non-null    object
 3   imin          397 non-null    object
 4   imax          397 non-null    object
 5   imean         397 non-null    object
 6   istd          397 non-null    object
 7   Normal        397 non-null    object
 8   Emboli        397 non-null    object
 9   BRAO          397 non-null    object
 10  CRAO          397 non-null    object
 11  BRVO          397 non-null    object
 12  CRVO          397 non-null    object
 13  Hemi-CRVO     397 non-null    object
 14  BDR-NPDR      397 non-null    object
 15  PDR           397 non-null    object
 16  ASR           397 non-null    object
 17  HTR           397 non-null    object
 18  Coats         397 non-null    object
 19  MA            397 non-null    object
 20  CNV           397 non-null    object
 21  UNDEF         397 non-null    object
 22  dcodez_id     397 non-null    object
 23  dcodez_short  397 non-null    object
 24  dcodez_desc   397 non-null    object
 25  dnotes        210 non-null    object
dtypes: object(26)
memory usage: 80.8+ KB

In [7]:
pdstats.dframe.describe()

,fname,fpath,ishape,imin,imax,imean,istd,Normal,Emboli,BRAO,...,ASR,HTR,Coats,MA,CNV,UNDEF,dcodez_id,dcodez_short,dcodez_desc,dnotes
count,397,397,397,397,397,397,397,397,397,397,...,397,397,397,397,397,397,397,397,397,210
unique,397,397,1,2,17,397,397,2,2,2,...,2,2,2,2,2,2,48,48,48,75
top,im0210,/mnt/externz/zRepoz/datasets/fundus/stare/im01...,"(605, 700, 3)",0,255,78.8666776859504,77.23802694212543,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,14,UNDEF,Unknown Diagnosis,Choroidal Neovascularization AND Age Related M...
freq,1,1,397,371,373,1,1,358,384,390,...,364,361,383,389,336,239,90,90,90,33

In [8]:
dtmp = pdstats.dframe.loc[:,'Normal':'dcodez_id']
dtmp['sumz'] = dtmp.loc[:,'Normal':'UNDEF'].sum(axis=1)
dtmp

,Normal,Emboli,BRAO,CRAO,BRVO,CRVO,Hemi-CRVO,BDR-NPDR,PDR,ASR,HTR,Coats,MA,CNV,UNDEF,dcodez_id,sumz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,0.00.00.00.00.00.00.01.00.00.00.00.00.00.00.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,13++9,0.00.00.00.00.00.00.00.00.01.00.00.00.01.00.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,14,0.00.00.00.00.00.00.00.00.00.00.00.00.00.01.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,14++3,0.00.00.01.00.00.00.00.00.00.00.00.00.00.01.0
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3++5,0.00.00.01.00.01.00.00.00.00.00.00.00.00.00.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,10++9,0.00.00.00.00.00.00.00.00.01.01.00.00.00.00.0
393,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2++1++9,0.01.01.00.00.00.00.00.00.01.00.00.00.00.00.0
394,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2++1++9,0.01.01.00.00.00.00.00.00.01.00.00.00.00.00.0
395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,14,0.00.00.00.00.00.00.00.00.00.00.00.00.00.01.0
396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,14,0.00.00.00.00.00.00.00.00.00.00.00.00.00.01.0

In [9]:
pd.__version__

'1.2.2'

In [12]:
import torch
import numpy as np

a = [1,2,3,4,5]
print(type(a), a)
aa = np.array(a)
print(type(aa), aa)
at = torch.tensor(a)
print(type(at), at)
aal = [aa*(i+1) for i in range(3)]
print(type(aal), aal)
atl = [at*(i+1) for i in range(3)]
print(type(atl), atl)
aalt = torch.tensor(aal)
print(type(aalt), aalt)

<class 'list'> [1, 2, 3, 4, 5]
<class 'numpy.ndarray'> [1 2 3 4 5]
<class 'torch.Tensor'> tensor([1, 2, 3, 4, 5])
<class 'list'> [array([1, 2, 3, 4, 5]), array([ 2,  4,  6,  8, 10]), array([ 3,  6,  9, 12, 15])]
<class 'list'> [tensor([1, 2, 3, 4, 5]), tensor([ 2,  4,  6,  8, 10]), tensor([ 3,  6,  9, 12, 15])]
<class 'torch.Tensor'> tensor([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15]])

In [1]:
import numpy as np

In [23]:
data_pipez = ['da', 'db', 'dc']
model_pipez = ['mx', 'my', 'mz']
# data_pipez = np.array(['a', 'b', 'c'])
# model_pipez = np.array(['x', 'y', 'z'])

data_pipez = [np.random.randint(0,100, size=2), np.random.randint(0,100, size=2), np.random.randint(0,100, size=2)]
model_pipez = [lambda x: print('identity: ', x), 
               lambda x: print( 'square: ', x**2), 
               lambda x: print('log: ', np.log(1/x))]

print( data_pipez, "\t", model_pipez)


# d_, m_ = np.meshgrid(data_pipez, model_pipez)
d_, m_ = np.meshgrid(range(len(data_pipez)), range(len(model_pipez)))
#print(d_, "\n", m_)

[array([ 3, 11]), array([97, 35]), array([65, 18])] 	 [<function <lambda> at 0x7f4aff69b4d0>, <function <lambda> at 0x7f4b00383cb0>, <function <lambda> at 0x7f4b00383c20>]

In [24]:
O_ = []
for x,y in zip(d_, m_):
#     print(x, "\t", y)
    for i, j in zip(x,y):
        O_.append( (data_pipez[i], model_pipez[j]) )
#         print( f"{i},{j}")
#         O_.append( (i,j))
        
O_

[(array([ 3, 11]), <function __main__.<lambda>(x)>),
 (array([97, 35]), <function __main__.<lambda>(x)>),
 (array([65, 18]), <function __main__.<lambda>(x)>),
 (array([ 3, 11]), <function __main__.<lambda>(x)>),
 (array([97, 35]), <function __main__.<lambda>(x)>),
 (array([65, 18]), <function __main__.<lambda>(x)>),
 (array([ 3, 11]), <function __main__.<lambda>(x)>),
 (array([97, 35]), <function __main__.<lambda>(x)>),
 (array([65, 18]), <function __main__.<lambda>(x)>)]

In [25]:
for d, m in O_:
    print(d)
    np.vectorize(m)(d)
    print("-----")

[ 3 11]
identity:  3
identity:  3
identity:  11
-----
[97 35]
identity:  97
identity:  97
identity:  35
-----
[65 18]
identity:  65
identity:  65
identity:  18
-----
[ 3 11]
square:  9
square:  9
square:  121
-----
[97 35]
square:  9409
square:  9409
square:  1225
-----
[65 18]
square:  4225
square:  4225
square:  324
-----
[ 3 11]
log:  -1.0986122886681098
log:  -1.0986122886681098
log:  -2.3978952727983707
-----
[97 35]
log:  -4.574710978503383
log:  -4.574710978503383
log:  -3.5553480614894135
-----
[65 18]
log:  -4.174387269895637
log:  -4.174387269895637
log:  -2.890371757896165
-----

In [26]:
for d, m in O_:
    print(d)
    for i in d:
        m(i)
    print("-----")

[ 3 11]
identity:  3
identity:  11
-----
[97 35]
identity:  97
identity:  35
-----
[65 18]
identity:  65
identity:  18
-----
[ 3 11]
square:  9
square:  121
-----
[97 35]
square:  9409
square:  1225
-----
[65 18]
square:  4225
square:  324
-----
[ 3 11]
log:  -1.0986122886681098
log:  -2.3978952727983707
-----
[97 35]
log:  -4.574710978503383
log:  -3.5553480614894135
-----
[65 18]
log:  -4.174387269895637
log:  -2.890371757896165
-----

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm 
from sklearn.pipeline import Pipeline

In [31]:
s = svm.SVC()
s.get_params().keys()

dict_keys(['C', 'break_ties', 'cache_size', 'class_weight', 'coef0', 'decision_function_shape', 'degree', 'gamma', 'kernel', 'max_iter', 'probability', 'random_state', 'shrinking', 'tol', 'verbose'])

In [32]:
l = LogisticRegression()
l.get_params().keys()

dict_keys(['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'])

In [35]:
p = Pipeline([
    ('svm', l),
    ('subZ', Pipeline([
        ('logit',  l)
    ]), )
])

p.get_params().keys()

TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'SVC()' (type <class 'sklearn.svm._classes.SVC'>) doesn't